
const productData = [
    "Destornillador Phillips",
    "Martillo de carpintero",
    "Llave inglesa ajustable",
    "Sierra circular",
    "Taladro eléctrico",
    "Tornillos de acero inoxidable",
    "Tuerca hexagonal",
    "Cinta métrica",
    "Escalera de aluminio",
    "Pistola de silicona",
    "Clavos para madera",
    "Pulidora angular",
    "Cadena de acero",
    "Cortadora de azulejos",
    "Grasa lubricante",
    "Guantes de trabajo",
    "Mascarilla protectora",
    "Pala de punta",
    "Carretilla de mano",
    "Brocas para metal",
    "Cinta de embalar",
    "Cepillo de alambre",
    "Trapo de limpieza",
    "Nivel de burbuja",
    "Lija de grano fino",
    "Pistola de clavos neumática",
    "Grapadora manual",
    "Destornillador de estrella",
    "Clavija eléctrica",
    "Cable de extensión",
    "Flexómetro",
    "Alicate de corte",
    "Cerradura de seguridad",
    "Pasadores de acero",
    "Herramienta de corte para tubos",
    "Pintura antihumedad",
    "Rodillo para pintar",
    "Barniz protector",
    "Cadena de seguridad",
    "Cerradura de combinación",
    "Cinta adhesiva de doble cara",
    "Pistola de pintura",
    "Llave de tubo",
    "Limpiador de desagües",
    "Cepillo de limpieza de tuberías",
    "Lámpara de trabajo LED",
    "Llave de vaso",
    "Grifo de agua",
    "Pegamento epoxi",
    "Cinturón de herramientas",
    "Escuadra de carpintero",
    "Remachadora manual",
    "Sierra de calar",
    "Taladro percutor",
    "Caja de herramientas",
    "Cizalla de corte",
    "Pistola de aire comprimido",
    "Guía para cortes rectos",
    "Cinta de pintor",
    "Marcador de carpintero",
    "Alicate de punta larga",
    "Cinta aislante",
    "Aceite lubricante",
    "Candado de seguridad",
    "Cadena antirrobo",
    "Bisagra de acero",
    "Candado de combinación",
    "Brocas para mampostería",
    "Disco de corte para metal",
    "Cable de acero",
    "Tornillo autorroscante",
    "Abrazadera de metal",
    "Casquillos para taladro",
    "Cubeta para pintura",
    "Rodillo de espuma",
    "Cúter de precisión",
    "Nivel láser",
    "Llave de impacto",
    "Linterna recargable",
    "Imán recogedor de objetos",
    "Sierra de mano",
    "Escalera telescópica",
    "Destornillador de punta plana",
    "Batería recargable",
    "Candado para bicicleta",
    "Caja de almacenamiento de herramientas",
    "Destornillador eléctrico",
    "Lápiz de carpintero",
    "Cable de red",
    "Candado para taquilla",
    "Escalera de mano plegable",
    "Llave de vaso de impacto",
    "Mordaza ajustable",
    "Brocas para madera",
    "Guantes de seguridad",
    "Taladro atornillador",
    "Serrucho de carpintero",
    "Caja de tornillos surtidos",
    "Pulidora orbital",
    "Lijadora de banda",
    "Brocas para hormigón",
    "Pasador de seguridad",
    "Candado para puerta",
    "Gafas de protección",
    "Mascarilla antipolvo"
];

module.exports = productData